apiVersion: solution.sap/v1
kind: Solution

metadata:
  name: greeting-agent-8a5f7
  version: "1.0.0"
  description: "AI agent that greets internal employees politely based on the time of day"

assets:
  - ref: ./assets/greeting-agent/asset.yaml
